version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  get:
    label: 'Get all the dependencies'
    cmds:
      - flutter pub get
  generate:
    label: 'Generate required files'
    deps: [get]
    cmds:
      - flutter pub run build_runner build --delete-conflicting-outputs
  generate-watch:
    label: 'Generate required files and watch'
    deps: [get]
    cmds:
      - flutter pub run build_runner build watch --delete-conflicting-outputs
  generate-launcher-icon:
    cmds:
      - flutter pub run flutter_launcher_icons -f {{.CLI_ARGS}}
  generate-splash-screen:
    cmds:
      - flutter pub run flutter_native_splash:create --flavor {{.CLI_ARGS}}
  run:
    label: 'Run with flavor'
    cmds:
      - flutter run --flavor {{.CLI_ARGS}} --dart-define=FLAVOR={{.CLI_ARGS}}
  release-run:
    label: 'Run with flavor'
    cmds:
      - flutter run --release --flavor {{.CLI_ARGS}} --dart-define=FLAVOR={{.CLI_ARGS}}
  build-apk:
    label: 'Build APK'
    cmds:
      - flutter build apk --flavor {{.CLI_ARGS}} --dart-define=FLAVOR={{.CLI_ARGS}}
  build-bundle:
    label: 'Build bundle'
    cmds:
      - flutter build appbundle --flavor {{.CLI_ARGS}} --dart-define=FLAVOR={{.CLI_ARGS}}
  build-ipa:
    label: 'Build IPA'
    cmds:
      - flutter build ipa --flavor {{.CLI_ARGS}}
  test:
    cmds:
      - flutter test