// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsoe-EcKcrNsANToRiGvce26l9wtkx2LM',
    appId: '1:1076611361348:android:b227cd834fb0b00f2aaa11',
    messagingSenderId: '1076611361348',
    projectId: 'native-dev-bd8e3',
    storageBucket: 'native-dev-bd8e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_teiPlE6s1BzxVYc9avIpQjRH3LCcTgI',
    appId: '1:1076611361348:ios:3642153076e6d3bb2aaa11',
    messagingSenderId: '1076611361348',
    projectId: 'native-dev-bd8e3',
    storageBucket: 'native-dev-bd8e3.appspot.com',
    androidClientId: '1076611361348-e6q4falahuk9l28a86791a7j010u0f2o.apps.googleusercontent.com',
    iosClientId: '1076611361348-2ejks4rpiahmsa4ls1pgu3hm0qq65blg.apps.googleusercontent.com',
    iosBundleId: 'me.benative.mobile',
  );
}
